# Generated by Django 5.2.14 on 2026-05-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='id',
            new_name='uuid',
        ),
    ]
