# Generated by Django 5.2.12 on 2026-05-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='steps',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
