# Generated by Django 5.2.13 on 2026-05-27 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_bug_bug_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='bug_id',
        ),
    ]
