# Generated by Django 5.2.13 on 2026-05-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_bug_bug_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='tc_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
