# Generated by Django 5.2.13 on 2026-05-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_testcase_tc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='bug_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
