# Generated by Django 5.2.12 on 2026-05-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_bug_bug_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='issue_type',
            field=models.CharField(choices=[('ui', 'UI Issue'), ('functionality', 'Functionality Issue')], default='functionality', max_length=20),
        ),
    ]
